### ISSUE TITLE
Show error message when deploying invalid dockerhub tag

### ISSUE THREAD

**Issue by webmaster128** [iov-one/chatbot#5]
Both

```
!deploy bns-faucet bns-faucet iov1/iov-faucet:v0.6.0
!deploy bcp-faucet bcp-faucet iov1/iov-faucet:v0.6.bbbuuugg
```

lead to the (success?) bot messages

```
deployment.extensions/bns-faucet image updated
```

```
deployment.extensions/bcp-faucet image updated
```

However, in the second case at some point an error must have occurred somewhere during the process. It would be good if this error was reported.

**Comment by ruseinov** [comment]
@webmaster128 Since kubernetes is eventually consistent it's a bit tricky.
But I think we can do 2 things:
1st - check if the image exists on github 
2nd - poke the service for status after a timeout (a minute I suppose and report the status) 
3rd - introduce a !deploy status command to show all the pods and their deployment status. 

Sounds good? I don't want to complicate this too much, but I can see how good feedback is beneficial.

The output you see now is the output of last successful command on kubernetes ( if there were errors on the way - it would report an error and stop execution). It's not super helpful, but gives you an idea that you managed to update the image.

**Comment by ruseinov** [comment]
@webmaster128 I have introduce an image check and also a delayed status report to see what's happening with the pods.
